#!/bin/sh

# This file is part of netfilter-persistent
# (was iptables-persistent)
# Copyright (C) 2009, Simon Richter <sjr@debian.org>
# Copyright (C) 2010, 2014 Jonathan Wiltshire <jmw@debian.org>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.

set -e

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

PROTECTED_CHAINS="PREROUTING POSTROUTING FORWARD DOCKER OUTPUT DOCKER-ISOLATION-STAGE-1 DOCKER-ISOLATION-STAGE-2"

BUILTIN_CHAINS_FILTER='^INPUT$|^FORWARD$|^OUTPUT$'

SKIP_DELETE_FILTER='^DOCKER-USER$'

SAVE_FILE=/etc/iptables/docker-rules.v4



load_rules()
{
    #load IPv4 rules
    if [ ! -f "${SAVE_FILE}" ]; then
        echo "Warning: skipping IPv4 (no rules to load)"
    else
        iptables-restore --noflush < $SAVE_FILE
    fi
}

save_rules()
{
    if [ ! "${IPTABLES_DOCKER_SKIP_SAVE}x" = "yesx" ]; then
        IPTABLE_FILTER=''
        for chain in $PROTECTED_CHAINS
        do
            IPTABLE_FILTER="${IPTABLE_FILTER}:${chain}"' |-A '"${chain}"' |'
        done
        IPTABLE_FILTER=$(echo "${IPTABLE_FILTER}" | sed -r 's/ \|$//')
        
        APPEND_FLUSH_SED='s/^:([^ ]+) (.*)/-F \1\n:\1 \2/'

        touch $SAVE_FILE
        iptables-save | grep -v -E "${IPTABLE_FILTER}" | sed -r "${APPEND_FLUSH_SED}"  > $SAVE_FILE
        chmod 0640 $SAVE_FILE
    fi
}

flush_rules()
{
    SKIPPED_CHAINS=''
    for chain in $PROTECTED_CHAINS
    do
        SKIPPED_CHAINS="${SKIPPED_CHAINS}^${chain}"'$|'
    done
    SKIPPED_CHAINS=$(echo "${SKIPPED_CHAINS}" | sed -r 's/\|$//')

    TABLES=$(iptables-save | sed -E -n 's/^\*//p')
    for table in $TABLES
        do
            CHAINS=$(iptables-save -t "${table}" | sed -E -n 's/^:([0-9A-Z\-]+).*/\1/p' | grep -v -E "${SKIPPED_CHAINS}"  || true)
            B_CHAINS=$(echo "${CHAINS}" | grep -E "${BUILTIN_CHAINS_FILTER}"  || true)
            D_CHAINS=$(echo "${CHAINS}" | grep -E -v "${BUILTIN_CHAINS_FILTER}" | grep -E -v "${SKIP_DELETE_FILTER}" || true)
            
        for chain in $B_CHAINS
        do
            # policy can't be set on user-defined chains
            iptables -t "${table}" -P "${chain}" ACCEPT
        done
        for chain in $CHAINS
        do
            iptables -t "${table}" -F "${chain}"
            iptables -t "${table}" -Z "${chain}"
        done
        for chain in $D_CHAINS
        do
            # you can't delete builtin and DOCKER-USER
            iptables -t "${table}" -X "${chain}"
        done
    done
}

case "$1" in
start|restart|reload|force-reload)
    load_rules
    ;;
save)
    save_rules
    ;;
stop)
    # Why? because if stop is used, the firewall gets flushed for a variable
    # amount of time during package upgrades, leaving the machine vulnerable
    # It's also not always desirable to flush during purge
    echo "Automatic flushing disabled, use \"flush\" instead of \"stop\""
    ;;
flush)
    flush_rules
    ;;
*)
    echo "Usage: $0 {start|restart|reload|force-reload|save|flush}" >&2
    exit 1
    ;;
esac