#!/bin/sh

set -e

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

SAVE_FILE=/etc/iptables/docker-rules.v6

IPTABLES_RESTORE=ip6tables-restore
IPTABLES_SAVE=ip6tables-save
IPTABLES=ip6tables

LOG="logger -s -t dockerfilter"

flush_rules()
{
    $LOG "flushing ipv6 rules"
    TABLES=$($IPTABLES_SAVE | sed -E -n 's/^\*//p')
    for table in $TABLES
    do
        # policy can only be set on builtin chains
        BUILTIN_CHAINS=$($IPTABLES_SAVE -t "${table}" | sed -E -n 's/^:([^ ]+) [^\-].*/\1/p')
        for chain in $BUILTIN_CHAINS
        do
            $IPTABLES -t "${table}" -P "${chain}" ACCEPT
        done
        
        $IPTABLES -t "${table}" -F
        $IPTABLES -t "${table}" -Z
        $IPTABLES -t "${table}" -X
    done
}

load_rules()
{
    if [ ! -f $SAVE_FILE ]; then
        $LOG "skipping IPv6 no file"
        return
    fi
    $LOG "loading IPv6 rules $SAVE_FILE"
    $IPTABLES_RESTORE < $SAVE_FILE
}

save_rules()
{
    if [ "${IPTABLES_DOCKER_SKIP_SAVE}" = "yes" ]; then
        $LOG "skipping saving IPv6"
        return
    fi
    $LOG "saving IPv6 rules $SAVE_FILE"
    $IPTABLES_SAVE > $SAVE_FILE
    chmod 0640 $SAVE_FILE
}



case "$1" in
start|restart|reload|force-reload)
    load_rules
    ;;
save)
    save_rules
    ;;
stop)
    echo "No flushing on stop"
    ;;
flush)
    flush_rules
    ;;
*)
    echo "Usage: $0 {start|restart|reload|force-reload|save|flush}" >&2
    exit 1
    ;;
esac